### ISSUE TITLE
Implement and test utils::Expected.h

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#111]
The `Expected` class is a stripped down copy of [`std::expected`](https://en.cppreference.com/w/cpp/utility/expected) from C++ 23. Its only interfaces should be those explicitly defined for `std::expected` and it should, to the best of our ability, replicate the behavior of `std::expected`. The goal is for `Expected` to eventually be replaced with `std::expected`.

**Comment by debruce** [comment]
I would like to work on this.

**Comment by debruce** [comment]
Per my Teams comments from late last week, there is a compilation problem from late last week due to the kind of thing that the Expected implementation is being asked to pass. I'm attaching the error message below:

ome/gzy3g3/projects/up-cpp/include/up-cpp/utils/Expected.h: In instantiation of ‘constexpr T uprotocol::utils::Expected<T, E>::value() const [with T = uprotocol::utils::callbacks::CalleeHandle<void, const uprotocol::v1::UMessage&>; E = uprotocol::v1::UStatus]’:
/home/gzy3g3/projects/up-cpp/test/coverage/transport/UTransportTest.cpp:144:55:   required from here
/home/gzy3g3/projects/up-cpp/include/up-cpp/utils/Expected.h:93:43: error: use of deleted function ‘uprotocol::utils::callbacks::CalleeHandle<RT, Args>::CalleeHandle(const uprotocol::utils::callbacks::CalleeHandle<RT, Args>&) [with RT = void; Args = {const uprotocol::v1::UMessage&}]’
   93 |                 return std::get<T>(storage);
      |                                           ^
In file included from /home/gzy3g3/projects/up-cpp/include/up-cpp/transport/UTransport.h:15,
                 from /home/gzy3g3/projects/up-cpp/test/include/UTransportMock.h:16,
                 from /home/gzy3g3/projects/up-cpp/test/coverage/transport/UTransportTest.cpp:13:
/home/gzy3g3/projects/up-cpp/include/up-cpp/utils/CallbackConnection.h:229:9: note: declared here
  229 |         CalleeHandle(const CalleeHandle&) = delete;

**Comment by debruce** [comment]
In this case, I believe Expected to copy a const reference of a callback object, and the client code has specifically deleted the ability the thing from a const reference. I suspect the only fix is to change the client code to allow copying of const references. This is a question for Greg.

**Comment by debruce** [comment]
I've gotten certain working fixes from Greg that allowed me to get rough coverage of test cases developed with C++23. There is a type casting problem for things like Expected<int,string> getting an unsigned int and similar cases. I'm going to set it aside, and return to the UTrasnport mocking test, and wait for feedback.

**Comment by debruce** [comment]
Hoping to get this merged today.
