### ISSUE TITLE
Add test mock for transport::UTransport

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#114]
The communication layer objects will all rely on a mocked UTransport implementation for testing. This will need to be implemented before tests can be written at the communication layer.

**Comment by PLeVasseur** [comment]
Or this one instead! :sweat_smile:

**Comment by debruce** [comment]
I'm going to spin up on this now.

**Comment by debruce** [comment]
https://github.com/eclipse-uprotocol/up-cpp/compare/main...debruce:feature/utransportmock?expand=1

**Comment by debruce** [comment]
That has a ton of stuff disabled to get it to compile, and tests nothing useful but explains the intended pattern.

**Comment by debruce** [comment]
I've created a pattern to test between the mocking class derived from UTransport and the gtest code. I've used this pattern to test construct/destruct, and the send method. Currently, I'm blocked on testing registerListener because the Expected implementation is unable to copy a const reference, and the Callee class that is an argument to registerListener has specifically deleted this copy constructor. I'm waiting for feedback from Greg, as to how to proceed.

**Comment by debruce** [comment]
Looking to pull in change for #152 from Greg, and test it next. Will provide review for Greg once done.

**Comment by debruce** [comment]
I have re-enabled uuri validation, and am about to push it. Message validation is still missing.

**Comment by debruce** [comment]
I've updated this quite a bit last Friday. I think the mock and test is in pretty good shape. I believe the message validator is disabled, and there is a merge conflict to resolve. Apart from that, I think this could possibly be merged soon.
