### ISSUE TITLE
Add ability to measure code coverage using gtest/ctest

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-cpp#83]

**Comment by gregmedd** [comment]
Some of the tests in these repos (e.g. testRpcClient, testPubSub) broad functional tests instead of unit tests. While they are still really important parts of the CI / PR testing process, they probably should not be included in the coverage reports. This is because they will generate broad coverage in a large, but do not make any specific assertions on the behavior of those lines.

I'd propose having some number of directories under the `test/` tree, such as `unit_test` and `functional_test`, that allow for easier separation of the test types. All tests can be run, but only the unit tests would contribute to the coverage report.

See: https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/pull/26#discussion_r1558144502

**Comment by MarkStokes71** [comment]
I'll take a look at this one.
