### ISSUE TITLE
Rust "C" api does not appear to support scatter/gather of attributes and message

### ISSUE THREAD

**Issue by debruce** [eclipse-uprotocol/up-cpp#86]
A zero copy sendmsg() syscall exists to gather data for network transmission. There seems to be no way this could be used to merge the attributes and payload from the client API. This seems like a bug.

**Comment by gregmedd** [comment]
Can you provide specificity on what part of this code base you are looking at? AFAIK, the only rust interaction is in [up-client-zenoh-cpp](/eclipse-uprotocol/up-client-zenoh-cpp).

Please verify this issue is filed in the right project, then add more detail so that we can understand where the issue exists and look at the relevant code.

**Comment by debruce** [comment]
Greg pointed out that this should really be in up-client-zenoh-cpp, since its implementation specific. Closing here and reopening with more details in the other repo in future.
